---
  
- hosts: server
  become: yes
  become_method: sudo

  tasks:

  - name: 1. Install Latest version HTTP/Apache RPMs
    yum: name=httpd state=present

  - name: 2. Copy the Standard index.html file
    copy: src=index.html dest=/var/www/html/index.html mode=0664
  #  notify: restart httpd service
  - name: Start web server
    service:
      name: httpd
      state: started
- hosts: mysql
  vars:
    mysql_root_password: myclave
  tasks:
  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    sudo: yes
    with_items:
    - python-mysqldb
    - mysql-server
  #- name: copy cnf
  #  copy: src=.my.cnf dest=~/.my.cnf owner=ubuntu mode=0644
  #  sudo: yes
  - name: Start the MySQL service
    sudo: yes
    service: 
      name: mysql 
      state: started
      enabled: true
  - name: update mysql root password for all root accounts
    sudo: yes
    mysql_user: 
      name: root 
      host: "{{ item }}" 
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost 

